### ISSUE TITLE
Зачем избыточные преобразования?

### ISSUE THREAD

**Issue by Muxamedin** [SanyaBoroda4/Hillel_Homeworks#1]
input уже возвращает нам строку - зачем же ее переводить это к int и потом нигде не использовать но в коде 2 раза 
из int конвертировать в троку ?

https://github.com/SanyaBoroda4/Hillel_Homeworks/blob/f01bd87a57d963cb03911dab7c890dfff0ee20c9/Lesson%204/Homework_task_1.py#L3
Рекомендация: 
- обратите внимение на требования задачи к выводу 
- input может содержать текст приглашение 
- вместо set котрые мы не проходили - рекомендую обратить внимание на методы строк 
.count()
.find()

**Comment by SanyaBoroda4** [comment]
Пофиксил первый вариант и сделал через метод .count

https://github.com/SanyaBoroda4/Hillel_Homeworks/blob/master/Lesson%204/Homework_task_1.py

**Comment by Muxamedin** [comment]
Что бы изменить оценку - нужно написать об изменениях в LMS 
будет -1 от максимума 


Mikel Bily
Staff Software Engineer
CloudBees, Inc.
